org: viniciusserverless
app: serverless-api
service: serverless-api
frameworkVersion: "4"

plugins:
  - serverless-plugin-datadog

custom: 
  tableName: "users-table-${sls:stage}"
  datadog: 
    site: datadoghq.com
    apiKeySecretArn: ${env:DD_API_KEY_SECRET_ARN}
    addLayers: true
    forwarder: true
    enableXrayTracing: true
    enableDDTracing: true
    enableDDLogs: true
    subscribeToAccessLogs: true

provider: 
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  profile: serverless-api
  environment:
    USERS_TABLE: ${self:custom.tableName}
    DD_TRACE_ENABLED: "true"
    DD_ENV: "dev"
    DD_SERVICE: "serverless-api"
    DD_VERSION: "1.0.0"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 
            - Fn::GetAtt: [UsersTable, Arn]
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: 
            - ${env:DD_API_KEY_SECRET_ARN}

functions: 
  api:
    handler: handler.handler
    events:
      - httpApi: "*"


resources: 
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema: 
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}